import Footer from "@/components/Footer/Footer";
import TopBar from "@/components/Navigation/TopBar";

import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
