// import Footer from "@/components/Footer/Footer";
// import TopBar from "@/components/Navigation/TopBar";
import ProfileNave from "@/components/Profile/ProfileNave";
// import "../globals.css";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex flex-col bg-slate-100 md:flex-row">
      <div className="mx-2 my-3 md:m-5">
        <ProfileNave
          user={{
            name: "Parvez Musharaf",
            email: "parvez@gmail.com",
            address: "Dhaka",
            profileImageUrl: "/profile.jpg",
          }}
        />
      </div>
      <div className="flex items-center first-letter justify-center flex-1 mx-2 my-3 md:m-5">
        {children}
      </div>
    </main>
  );
}

// import type { ReactElement } from "react";
// import Layout from "../components/layout";
// import NestedLayout from "../components/nested-layout";
// import type { NextPageWithLayout } from "./_app";

// const Page: any = () => {
//   return <p>hello world</p>;
// };

// import page from "./page";

// page.getLayout = function getLayout(page: ReactElement) {
//   return (
//     <div>
//       <ProfileNave
//         user={{
//           name: "Parvez Musharaf",
//           email: "parvez@gmail.com",
//           address: "Dhaka",
//           profileImageUrl: "/profile.jpg",
//         }}
//       />

//       {page}
//     </div>
//   );
// };

// export default page;
